language: go

go: 1.5.2

sudo: required

services:
  - docker

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'CREATE USER tests WITH CREATEDB;' -U postgres

install:
  - make setup

script:
  - make
  - make docker-build
  - make docker-tag-travis
  - make docker-push
