#!/usr/bin/env bash

set -e

function main {
  case "$1" in

  clean)
    clean
    ;;

  setup)
    setup
    ;;

  generate)
    generate
    ;;

  build)
    build
    ;;

  test)
    test
    ;;

  analyse)
    analyse
    ;;

  docker-build)
    docker-build
    ;;

  *)
    help
    exit 1
    ;;

  esac
}

function clean {
  go clean
}

function setup {
  go get -t -v
  go get -v github.com/jteeuwen/go-bindata/...
}

function generate {
  go-bindata -pkg main -o bindata.go db/migrations/
}

function build {
  generate
  go build -o weather-thingy-data-service
}

function test {
  go test
}

function analyse {
  go tool vet -all -shadow .
}

function docker-build {
  echo "Compiling..."
  CGO_ENABLED=0 GOOS=linux go build -o weather-thingy-data-service-amd64-linux -a -installsuffix cgo .

  echo "Building image..."
  docker build --tag=charleskorn/weather-thingy-data-service .
}

function help {
  echo "Usage: "
  echo " clean         clean up any files generated by the build process"
  echo " setup         install any dependencies"
  echo " generate      generate files used by the build process"
  echo " build         build the application"
  echo " test          test the application"
  echo " docker-build  build a Docker image for the application"
  echo " help          print this help information"
}

main $1
