#!/usr/bin/env bash

set -e

GO_VERSION="1.4.2"

function main {
  case "$1" in
  check)
    check
    ;;

  clean)
    clean
    ;;

  setup)
    setup
    ;;

  generate)
    generate
    ;;

  build)
    build
    ;;

  test)
    test
    ;;

  analyse)
    analyse
    ;;

  snap-setup)
    snap-setup
    ;;

  *)
    help
    exit 1
    ;;

  esac
}

function check {
  VERSION_STRING=$(go version)

  if [[ "$VERSION_STRING" != "go version go$GO_VERSION "* ]]; then
    echo "Go version $GO_VERSION not found."
    exit 1
  fi
}

function clean {
  go clean
}

function setup {
  go get -t -v
}

function generate {
  go-bindata -pkg main -o bindata.go db/migrations/
}

function build {
  generate
  go build weather-thingy-data-service
}

function test {
  go test
}

function analyse {
  go tool vet -all -shadow .
}

function snap-setup {
  # From https://fourcube.github.io/golang/2014/12/12/go-on-snap-ci.html
  # Pin this script in your build steps.
  GO_OS="linux"
  GO_ARCH="amd64"

  export GOPATH="$SNAP_CACHE_DIR/go-$GO_VERSION/gopath"
  export GOROOT="$SNAP_CACHE_DIR/go-$GO_VERSION"
  export GOBIN="$GOPATH/bin"
  export PATH="$PATH:$GOBIN:$GOROOT/bin"

  # If we have not downloaded go yet, do it and put it in the cache
  if [ ! -d $GOROOT ] ; then
    echo "Go not found in $GOROOT, downloading and installing..."
    mkdir $GOROOT

    GO_ARTIFACT="go$GO_VERSION.$GO_OS-$GO_ARCH.tar.gz"
    LOCAL_PATH="$SNAP_CACHE_DIR/$GO_ARTIFACT"

    echo "Downloading $GO_ARTIFACT..."
    wget -O $LOCAL_PATH https://storage.googleapis.com/golang/$GO_ARTIFACT

    echo "Extracting files..."
    tar -xzf $LOCAL_PATH --strip 1 -C $GOROOT

    echo "Installing go vet..."
    go get golang.org/x/tools/cmd/vet

    echo ""
  fi

  echo "Installing Mercurial..."
  sudo yum install --assumeyes mercurial

  echo "Environment summary:"
  go env

  echo ""
}

function help {
  echo "Usage: "
  echo " clean       clean up any files generated by the build process"
  echo " setup       install any dependencies"
  echo " generate    generate files used by the build process"
  echo " build       build the application"
  echo " test        test the application"
  echo " snap-setup  sets up a Snap CI build environment"
  echo " help        print this help information"
}

main $1
